### ISSUE TITLE
A possible Python bug causes re.sub() to fail

### ISSUE THREAD

**Issue by dzarda** [pl-ca/ClangAutoComplete#29]
I came across this while setting ClangAutoComplete with Sublime 3114. The following exception is thrown on each completion.
`
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 377, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "C:\Users\Dzarda\AppData\Roaming\Sublime Text 3\Packages\ClangAutoComplete\ClangAutoComplete.py", line 105, in on_query_completions
    self.load_settings()
  File "C:\Users\Dzarda\AppData\Roaming\Sublime Text 3\Packages\ClangAutoComplete\ClangAutoComplete.py", line 86, in load_settings
    include_dir = re.sub("(\$project_base_path)", project_path, include_dir)
  File "./python3.3/re.py", line 170, in sub
  File "./python3.3/re.py", line 309, in _subx
  File "./python3.3/re.py", line 296, in _compile_repl
  File "./python3.3/sre_parse.py", line 801, in parse_template
sre_constants.error: missing group name
`

**Comment by pl-ca** [comment]
I'll be honest and say that I have no idea what is causing this. What platform are you running this on?

**Comment by dzarda** [comment]
Windows 7 64bit
