### ISSUE TITLE
Got errrors on python

### ISSUE THREAD

**Issue by Rapiz1** [pl-ca/ClangAutoComplete#32]
OS: Windows 10 64-bits

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 591, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "C:\Users\Rapiz\AppData\Roaming\Sublime Text 3\Packages\ClangAutoComplete\ClangAutoComplete.py", line 105, in on_query_completions
    self.load_settings()
  File "C:\Users\Rapiz\AppData\Roaming\Sublime Text 3\Packages\ClangAutoComplete\ClangAutoComplete.py", line 86, in load_settings
    include_dir = re.sub("(\$project_base_path)", project_path, include_dir)
  File "./python3.3/re.py", line 170, in sub
  File "./python3.3/re.py", line 314, in filter
  File "./python3.3/sre_parse.py", line 870, in expand_template
sre_constants.error: invalid group reference

**Comment by pl-ca** [comment]
It is the first time I see this, I assume it is related to how format of the 'project_path' variable on Windows. Whenever I get a chance I will try to reproduce it.

Meanwhile you can comment that line out (#86) in the file ClangAutoComplete.py. It will prevent you from using the '$project_base_path' variable in your settings but otherwise the rest should work.
